### PR TITLE
Submit for review

### PR DESCRIPTION
**Pull request by 1ba1**

### CODE REVIEW

**Comment by heyapricot** [comment]
# Truth or nil 📭

👋🏼 Hello! You built the enumerables! Yay! however, there is trouble with my_any? and my_none?. Please take a look and after that submit a new code review request. Thanks!

**Review by heyapricot — CHANGES_REQUESTED** [review]
# My_none? is working but my_any still raises an error
I've raised an issue regarding `my_any?`. Please fix and after that submit a new code review request. Thanks!

**Comment by 1ba1** [comment]
Modified my_any method, submitting again for the review.

**Comment by heyapricot** [comment]
# You did it! 🙌🏼
Hey Team! Well done completing one of your firsts ruby projects. How do you feel about it?
No need from my side for further review. Let's move to the next project 🚀

**Review by heyapricot — APPROVED** [review]

**Comment by heyapricot** [comment]
Side note: You may want to listen to the suggestions of stickler. At least the redundant-self ones

**Pull request merged**
